function [s0,s1]=split_block(kemb2,s)           %    Split block using a pseudo random sequence generated by kemb2
    s0=[];
    s1=[];   
    rng(kemb2);
    s_values=randi(s*s,s,s);                    %    Pseudo random sequence generated by kemb2
    for i=1:size(s_values,1)
        for j=1:size(s_values,2)
            if mod(s_values(i,j),2)==0
                s0=cat(1,s0,[i,j]);
            else
                s1=cat(1,s1,[i,j]);    
            end
        end
    end
end