function streamkey=streamkey_gen(seed,img_row,img_col)      %   Generates stream key for image encryption
    rng(seed);
    streamkey=uint8(randi(255,img_row,img_col));            %   Pseudo random sequence generated by seed
end